//
//
// ALKCustomEventMap.swift
// ApplozicSwift
//
// Created by ___Sathyan Elangovan___ on 09/12/21
import Foundation
public enum ALKCustomEventMap: String {
    case EVENT_ON_MESSAGE_SEND = "ON_MESSAGE_SEND"
    case EVENT_ON_FAQ_CLICK = "ON_FAQ_CLICK"
    case EVENT_ON_GREETING_MESSAGE_NOTIFICATION_CLICK = "ON_GREETING_MESSAGE_NOTIFICATION_CLICK"
    case EVENT_ON_NOTIFICATION_CLICK = "ON_NOTIFICATION_CLICK"
    case EVENT_ON_RESOLVE_CLICK = "ON_RESOLVE_CLICK"
    case EVENT_ON_START_NEW_CONVERSATION_CLICK = "ON_START_NEW_CONVERSATION_CLICK"
    case EVENT_ON_ATTACHMENT_ICON_CLICK = "ON_ATTACHMENT_ICON_CLICK"
    case EVENT_ON_VOICE_ICON_CLICK = "ON_VOICE_ICON_CLICK"
    case EVENT_ON_LOCATION_ICON_CLICK = "ON_LOCATION_ICON_CLICK"
    case EVENT_ON_RATE_CONVERSATION_CLICK = "ON_RATE_CONVERSATION_CLICK"
    case EVENT_ON_RATE_CONVERSATION_EMOTIONS_CLICK = "ON_RATE_CONVERSATION_EMOTIONS_CLICK"
    case EVENT_ON_SUBMIT_RATING_CLICK = "ON_SUBMIT_RATING_CLICK"
    case EVENT_ON_CHAT_CLOSE_CLICK = "ON_CHAT_CLOSE_CLICK"
    case EVENT_ON_CHAT_OPEN_CLICK = "ON_CHAT_OPEN_CLICK"
    case EVENT_ON_RESTART_CONVERSATION_CLICK = "ON_RESTART_CONVERSATION_CLICK"
    case EVENT_ON_RICH_MESSAGE_CLICK = "ON_RICH_MESSAGE_CLICK"
}

