project ‘ApplozicSwiftDemo.xcodeproj'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'ApplozicSwiftDemo' do
    pod 'ApplozicSwift', :path => '../ApplozicSwift.podspec'
    pod 'Applozic', :git => 'https://github.com/AppLozic/Applozic-Chat-iOS-Framework.git', :branch => 'replyMessageFetch'
    pod 'SwiftLint'
end

target 'ApplozicSwiftDemoTests' do
    pod 'ApplozicSwift', :path => '../ApplozicSwift.podspec'
    pod 'Nimble'
    pod 'Quick'
    pod 'Nimble-Snapshots'
    # Added to test target, as SwiftFormat will replace the files
    # every time we build, which will clear the undo history.
    pod 'SwiftFormat/CLI'
end
