project 'ApplozicSwiftDemo.xcodeproj'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'ApplozicSwiftDemo' do
    pod 'ApplozicSwift', :path => '../ApplozicSwift.podspec'
    pod 'ApplozicCore', :git => 'https://github.com/AppLozic/Applozic-Chat-iOS-Framework.git', :branch => 'core-ui-test'
    pod 'SwiftLint'
end

target 'ApplozicSwiftDemoTests' do
    pod 'ApplozicSwift', :path => '../ApplozicSwift.podspec'
    pod 'ApplozicCore', :git => 'https://github.com/AppLozic/Applozic-Chat-iOS-Framework.git', :branch => 'core-ui-test'
    pod 'Nimble'
    pod 'Quick'
    pod 'Nimble-Snapshots'
    # Added to test target, as SwiftFormat will replace the files
    # every time we build, which will clear the undo history.
    pod 'SwiftFormat/CLI'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
